### ISSUE TITLE
Selecting an item from history adds the history index as well

### ISSUE THREAD

**Issue by eblis** [chrisant996/clink-fzf#17]
This might be something on my end, with my configuration, but recently when I select a history entry (after pressing Ctrl + R) in clink i get a list of entries like so:
![image](https://github.com/chrisant996/clink-fzf/assets/540188/44a8dab6-ff50-41cc-b6ed-3942a677ce78)
If I select one of the entries in the history the command prompt changes to:
![image](https://github.com/chrisant996/clink-fzf/assets/540188/d2045e44-1eb9-4c29-830c-3c162cc783cd)

It adds the history index of the selected command to the command prompt

**Comment by chrisant996** [comment]
The screen shots are too small to see what's happening.

But I think you have fzf set up, and I think you don't have the latest fzf.lua script.

UPDATE: Oh haha I initially missed that this issue is in the clink-fzf repo. You don't have the latest version.

**Comment by eblis** [comment]
Ah, yes, forgot to mention.
I have clink and clink-gizmos (which includes fzf.lua)

I'll update and report back

**Comment by eblis** [comment]
Everything ok with the latest fzf.lua script. Sorry for the trouble.
