### ISSUE TITLE
ERROR: Setting 'fzf.default_bindings' not found.

### ISSUE THREAD

**Issue by SMUsamaShah** [chrisant996/clink-fzf#19]
- fzf.exe is in system path and I can execute fzf.exe just fine from cmder.
- Placed fzf.lua in `cmder\vendor\conemu-maximus5\ConEmu\Scripts` (also tried `cmder\config\profile.d`)
- Then ` clink set fzf.default_bindings true` 
It returns `ERROR: Setting 'fzf.default_bindings' not found.`

What am i doing wrong? 

Clink version  : 1.6.13.eb61b2
Cmder version : Version 1.3.24.236

**Comment by chrisant996** [comment]
You must have an old version of the script,

Try updating it.

**Comment by chrisant996** [comment]
Oh, no, it's probably one of these: 

- Have you put it in a folder that's listed as a script folder in `clink info`?
- Have you restarted Clink after copying the script?

**Comment by SMUsamaShah** [comment]
Oh! Thanks very much. Please add the `clink info` to find scripts dir in your readme. I put the fzf.lua in `cmder\config` dir as reported by `clink info` and it just worked.

**Comment by chrisant996** [comment]
Ok but please consider reading the Clink docs.

E.g.
- [Location of Lua Scripts](https://chrisant996.github.io/clink/clink.html#lua-scripts-location)
- [File Locations](https://chrisant996.github.io/clink/clink.html#filelocations)
