### ISSUE TITLE
Need to surround path-names with quotes for special characters

### ISSUE THREAD

**Issue by AKil47** [chrisant996/clink-fzf#24]
## Context

Windows allows for the `&` to be in folder names. This causes a problem when trying to `cd` into the directory, since the `&` is used to split commands in windows.

This is mitigated by wrapping the path in quotes. For example:

This fails:

```
cd OneDrive - Texas A&M University
```

While this succeeds:
```
cd "OneDrive - Texas A&M University"
```

## Issue

The issue is that this plugin does **not** wrap the output of `fzf` in quotes, causing issues for file paths with ampersands (or other characters that are allowed in folders but cause issues in the command line).

## Solution

Wrapping the output with quotes should solve the issue. I'm happy to try to implement this myself, but I don't see any mention of Contribution rules in the `README.md` so I am unsure on how to proceed.

**Comment by chrisant996** [comment]
Please share specific repro steps.

Which fzf integration command(s) are you invoking?
What keys are you pressing?  For example, <kbd>Tab</kbd>?  <kbd>Alt-C</kbd>?  <kbd>Ctrl-T</kbd>?  Something else?

**Comment by chrisant996** [comment]
I'll assume you mean you press <kbd>Alt-C</kbd> and that the `fzf_directory` command doesn't apply quotes when needed.

If that's not what you mean, please let me know.

**Comment by chrisant996** [comment]
03b09fa12afec8b44d584f4dde74d39a9815709a added quoting to <kbd>Alt-C</kbd>.
