### ISSUE TITLE
[help] getting help text to show in fzf description

### ISSUE THREAD

**Issue by plutonium-239** [chrisant996/clink-fzf#25]
I use the fzf plugin through the `clink-gizmos`. However, when I try to complete an argument for a program (take for example `sed`), I do see the various options in the `fzf` "dropdown" but not their descriptions. Perhaps this image explains it better:

![image](https://github.com/user-attachments/assets/7c052d29-980e-4362-b8ed-5a3eba685f60)
The right hand side doesn't have any help text.

I think this is probably because of a wrong config on my side but I can't narrow it down.

**Comment by chrisant996** [comment]
The fzf.lua script does not currently support flag descriptions. 

It's something I might try to add in the future, so I'll keep this issue open for tracking purposes.

**Comment by chrisant996** [comment]
Oh!  I'm so wrong!  I already added support. 

`clink set fzf.show_descriptions true`

But it's not mentioned in the README.  I'll try to add some documentation later this week.

Also there's a `fzf.color_descriptions` setting.

**Comment by plutonium-239** [comment]
Thanks, that was it!

I can get descriptions for supported programs (and also current values for clink settings!) now:

![image](https://github.com/user-attachments/assets/93bbcaa6-111f-4e5e-a925-fbdcb40ed8cb)
![image](https://github.com/user-attachments/assets/f8d54147-7008-4d2a-9eef-1a07175c22d5)
