### ISSUE TITLE
can't execute 'fzf_directory'; not a function

### ISSUE THREAD

**Issue by theperiscope** [chrisant996/clink-fzf#4]
I get a `can't execute 'fzf_directory'; not a function`  error using latest `fzf.lua` source (2022-06-18). When I revert to one from around March 30th error disappears -- any idea what may be causing it? Same happened on a different PC (Windows 11 on one, Windows 10 on the other). I think my setup is fairly vanilla Cmder/Clink with latest versions. I attached here the two versions I have.

[fzf-mar30.lua.txt](https://github.com/chrisant996/clink-fzf/files/8933751/fzf-mar30.lua.txt)
[fzf-jun18.lua.txt](https://github.com/chrisant996/clink-fzf/files/8933752/fzf-jun18.lua.txt)

**Comment by chrisant996** [comment]
I'm not able to reproduce that with Clink v1.3.24.  The <kbd>Alt</kbd>-<kbd>c</kbd> for `fzf_directory` works fine for me.

What version of Clink are you using?
Might you have more than one `fzf.lua` file that's getting loaded?
Or might another `.lua` file be interfering somehow?

The `fzf_directory` function exists in both of the Lua files you attached.

**Comment by theperiscope** [comment]
My clink is version `1.3.13.24b02e` (latest installed using chocolatey) and I have just one copy of fzf.lua. It is interesting issue -- because just swap of the file fixes it -- and at the same time I do see that the function is in both. I'll keep digging later today and report back any discoveries... one thing I wanted to check/compare file encodings -- in the past that has been a source of difficult bugs for me. Another test I want to try is with almost blank file and/or simple blank function stubs.

**Comment by theperiscope** [comment]
Started working with new version without me clearly understanding 'why', as I was starting to play with the files. I'll close issue for now, thank you for responding and spending time on it.
