### ISSUE TITLE
fzf.lua and arghelper module

### ISSUE THREAD

**Issue by theperiscope** [chrisant996/clink-fzf#5]
After I installed a recent version of `fzf.lua` I received a `module 'arghelper' not found` error (Windows 10.0.19044.1889).

I was able to resolve it by downloading the `arghelper.lua` file and placing it a `modules` folder where the `fzf.lua` is located. The "how to install" section of the Readme.md could also use a quick update.

**Comment by chrisant996** [comment]
Oh, I see.  The files are present in the repo, but the instructions are outdated.  I will probably just alter fzf.lua to not depend on arghelper.lua at all.

**Comment by theperiscope** [comment]
Thanks for quick fix Chris, I installed the latest update, removed `modules` folder, and everything is well.
